# This is a docker-compose file for a development environment of ODMF. Not to be used in production

# Features:
#
# - The ODMF source code is git cloned to a mounted directory (./app/src) and can be edited there (and committed)
# - Python's site packages are stored permanently in a docker volume to avoid repeated downloading of dependencies
#   to switch this feature of, comment the services->web->volumes->site-packages line out. If you want to use additional
#   packages, add them to the requirements.txt file
# - The database port is published at 5432 to connect to it using some db frontend

version: '3.4'

services:
  web:
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    build:
      context: ./services/odmf
      args:
        SOURCE_URL: ${SOURCE_URL:-odmf}

    environment:
      - DB_URL=$DB_TYPE://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
      - ODMF_ADMIN_PW
      - ODMF_DEFAULT_TIMEZONE
      - ODMF_NAME
      - ODMF_PORT
      - ODMF_ROOT_URL
    volumes:
      - ./app/:/srv/odmf/
      - ./backup/:/var/backup
      # Cooment this line if you do not want to store the site-packages permanently. Do not forget to delete the volume
      - site-packages:/usr/local/lib/python3.9/site-packages
    ports:
      - ${ODMF_PORT}:${ODMF_PORT}
    depends_on:
      - db
    restart: "no"
    working_dir: /srv/odmf
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER:-db_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-db_passw}
      - POSTGRES_DB=${DB_NAME:-odmf}
    ports:
      - 5432:5432
    restart: unless-stopped
volumes:
  postgres_data:
  site-packages:

