#!/bin/bash
DIR=$(dirname "$0")
if [ -z "$1" ]; then
  echo "docker-exec - Execute a command inside the running odmf web container"
  echo "Usage: sudo ./docker-exec ..."
  echo ""
  echo "Examples"
  echo "sudo ./docker-exec odmf interactive   # Start an interactive Python shell with tools for odmf management"
  echo "sudo ./docker-exec bash               # Start a bash session in the container"
  echo "sudo ./docker-exec db-backup.sh       # Create a new backup of the database"
  echo "sudo ./docker-exec db-edit.sh         # Start an interactive psql terminal to edit the database"
  echo ""
  echo "Permissions: Usually all members of the odmf-... group should have special sudo rights for this script."
fi
docker-compose -f $DIR/docker-compose.yml docker-exec web "$1"