#!/bin/bash
# Restores the database from a backup made with /db-backup
set -e
DB_URL="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/$POSTGRES_DB"
PREFIX=$1
PREFIX=${PREFIX:-.}
TABLES=$(</var/backup/tables)
RTABLES=$(tac -s' '<<<$TABLES)
echo "$PREFIX/[TABLE].[ODMF_NAME].sql.gz"
for T in $RTABLES
do
   echo "Delete $T"
   psql -d $DB_URL -c "DELETE FROM $T;"
done
for T in $TABLES
do
  echo "$PREFIX/$T.*.sql.gz* -> $T"
  gunzip -c $PREFIX/$T.*.sql.gz* | psql -1 -d $DB_URL
done